# uncomment this line for openshift
# - openshift_scc.yaml
# uncomment this line if prometheus deployed
resources:
- exporter.yaml
- prometheus_service_monitor.yaml

# add this line to allow ci
# - ./patch/patch-ci.yaml
# add this for kind provider ci
# - ./patch/patch-kind.yaml
# add this line for bm case
# - ./patch/patch-bm.yaml
# add this line to enable estimator sidecar
patchesStrategicMerge:
- ./patch/patch-estimator-sidecar.yaml
# add this line for openshift patch
# - ./patch/patch-openshift.yaml
# add this line for rootless patch
# - ./patch/patch-rootless.yaml
# add this line for qat patch
# - ./patch/patch-qat.yaml

secretGenerator:
- files:
  - ./redfish.csv
  name: redfish

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: kepler
  newName: quay.io/sustainable_computing_io/kepler
  newTag: latest
- name: kepler_model_server
  newName: quay.io/sustainable_computing_io/kepler_model_server
  newTag: latest

vars:
- fieldref:
    fieldPath: metadata.name
  name: KEPLER_NAMESPACE
  objref:
    kind: Namespace
    name: system
    version: v1
- fieldref:
    fieldPath: data.KEPLER_LOG_LEVEL
  name: KEPLER_LOG_LEVEL
  objref:
    kind: ConfigMap
    name: kepler-cfm
    version: v1
- fieldref:
    fieldPath: data.PROMETHEUS_SCRAPE_INTERVAL
  name: PROMETHEUS_SCRAPE_INTERVAL
  objref:
    kind: ConfigMap
    name: kepler-cfm
    version: v1

configurations:
- ./kustomizeconfig.yaml
