{
 "title": "Kepler Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pod_energy_stat, pod_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pod_energy_stat{pod_namespace=\"$namespace\"}, pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Current Energy Consumption (kW.s in 1 minute)",
   "type": "timeseries",
   "description": "The kW.s in 1 minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "20*rate(pod_energy_current{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/1000000000",
     "legendFormat": "Total"
    },
    {
     "expr": "20*rate(pod_cpu_energy_current{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/1000000000",
     "legendFormat": "CPU"
    },
    {
     "expr": "20*rate(pod_dram_energy_current{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/1000000000",
     "legendFormat": "DRAM"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW.s)",
   "type": "timeseries",
   "description": "Total kW.s Consumed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pod_energy_total{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/1000000000",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(pod_cpu_energy_total{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/1000000000",
     "legendFormat": "CPU"
    },
    {
     "expr": "rate(pod_dram_energy_total{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/1000000000",
     "legendFormat": "DRAM"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW.s) in $namespace",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "20*rate(pod_energy_total{pod_namespace=\"$namespace\"}[24h])/1000000000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW.s) in $namespace",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "20*sum(rate(pod_energy_total{pod_namespace=\"kepler\"}[24h]))/1000000000",
     "legendFormat": "kepler"
    },
    {
     "expr": "20*sum(rate(pod_energy_total{pod_namespace=\"openshift-dns\"}[24h]))/1000000000",
     "legendFormat": "openshift-dns"
    },
    {
     "expr": "20*sum(rate(pod_energy_total{pod_namespace=\"kube-system\"}[24h]))/1000000000",
     "legendFormat": "kube-system"
    },
    {
     "expr": "20*sum(rate(pod_energy_total{pod_namespace=\"openshift-ingress\"}[24h]))/1000000000",
     "legendFormat": "openshift-ingress"
    },
    {
     "expr": "20*sum(rate(pod_energy_total{pod_namespace=\"openshift-service-ca\"}[24h]))/1000000000",
     "legendFormat": "openshift-service-ca"
    },
    {
     "expr": "20*sum(rate(pod_energy_total{pod_namespace=\"system\"}[24h]))/1000000000",
     "legendFormat": "system"
    }
   ]
  }
 ]
}