{
 "title": "Kubernetes power usage using Scaphandre",
 "description": "Show Kubernetes cluster power usage measured with Scaphandre.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Processes using > 0.01W",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts / 1000000 > 0.01",
     "legendFormat": "{{ exe }}"
    }
   ]
  },
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Kubernetes Energy Usage\n\nPower consumption metrics for Kubernetes clusters using Scaphandre. https://github.com/hubblo-org/scaphandre"
   }
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "scaph_host_power_microwatts / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Scaphandre",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"scaphandre\"} / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"prometheus\"} / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Kubernetes Control Plane",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=~\"etcd|kube-apiserver|kube-controller|kube-proxy|kube-scheduler|kubelet\"} / 1000000",
     "legendFormat": "{{ exe }}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"grafana-server\"} / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"dockerd\"} / 1000000",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  }
 ]
}