global:
    scrape_interval: 1s
scrape_configs:

    # KAFKA BROKER SCRAPERS
    -   job_name: kafka
        metrics_path: /metrics
        static_configs:
            - targets:
                - kafka_broker_1:11001
                - kafka_broker_2:11001
                - kafka_broker_3:11001