version: '3.7'
services:
  dataset-feeder:
    build: .
    network_mode: "host"
    volumes:
      - ./datasets:/datasets
    command:
      - --fps
      - "5"
      - --repeat
      - '1'
      - --dataset
      - "./draft_v0.1.hdf5"
      - --delay
      - "1"
      - --server
      - "localhost:10001,localhost:10002,localhost:10003"
      - --max_vehicles
      - '10'
      - --max_frames
      - '-1'
      - --verbose


