{
 "title": "Ensure Project Dashboard Copy",
 "description": "Ensure Project Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" }
  ]
 },
 "panels": [
  { "title": "WORKLOAD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "KAFKA TOPIC: BYTES IN/OUT (+-3 MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"yolo_input\"}[1m]))by(topic)",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"yolo_input\"}[1m]))by(topic) * -1",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "CUMULATIVE WORKER CPU USAGE (0-500%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"worker.*\",mode!=\"idle\"}[30s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"worker.*\"}[30s])))) * 100)",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "OVERVIEW: POD CPU SECONDS",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\"}[1m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CUMULATIVE WORKER WATTS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(kepler_node_package_joules_total{instance=~\"worker.*\",mode=\"dynamic\"}[10s]))",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "CUMULATIVE WORKLOAD PODS (0-34)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) - count(kube_pod_info{namespace=~\"kube-system|kepler|monitoring|kafka\"})",
     "legendFormat": "Num Pods"
    }
   ]
  },
  {
   "title": "MASTER: CPU% (0-100)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"master\",mode!=\"idle\"}[30s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"master\"}[30s])))) * 100",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "WORKER 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "WORKER 1: WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker1\",mode=\"dynamic\"}[10s])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "WORKER 1: CPU% (0-100)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker1\",mode!=\"idle\"}[30s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker1\"}[30s])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "WORKER 1: POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker1\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WORKER 1: NUM PODS (0-5)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker1\"}) - count(kube_pod_info{node=\"worker1\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    },
    {
     "title": "WORKER 1: POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker1\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "WORKER 2: WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker2\",mode=\"dynamic\"}[30s])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "WORKER 2: CPU% (0-100)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker2\",mode!=\"idle\"}[30s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker2\"}[30s])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "WORKER 2: POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker2\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WORKER 2: NUM PODS (0-5)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker2\"}) - count(kube_pod_info{node=\"worker2\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    },
    {
     "title": "WORKER 2: POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker2\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "WORKER 3: WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker3\",mode=\"dynamic\"}[30s])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "WORKER 3: CPU% (0-100)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker3\",mode!=\"idle\"}[30s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker3\"}[30s])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "WORKER 3: POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker3\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WORKER 3: NUM PODS (0-5)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 22 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker3\"}) - count(kube_pod_info{node=\"worker3\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    },
    {
     "title": "WORKER 3: POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker3\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "WORKER 4: WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker4\",mode=\"dynamic\"}[30s])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "WORKER 4: CPU% (0-100)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker4\",mode!=\"idle\"}[30s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker4\"}[30s])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "WORKER 4: POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker4\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WORKER 4: NUM PODS (0-5)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker4\"}) - count(kube_pod_info{node=\"worker4\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    },
    {
     "title": "WORKER 4: POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker4\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "WORKER 5: WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker5\",mode=\"dynamic\"}[30s])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "WORKER 5: CPU% (0-100)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker5\",mode!=\"idle\"}[30s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker5\"}[30s])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "WORKER 5: POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker5\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WORKER 5: NUM PODS (0-5)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker5\"}) - count(kube_pod_info{node=\"worker5\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    },
    {
     "title": "WORKER 5: POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker5\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}