apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/sustainable-computing-io/kepler-model-server/manifests/server

images:
- name: kepler_model_server
  newName: quay.io/sustainable_computing_io/kepler_model_server
  newTag: latest
