{
 "title": "Ensure Project Dashboard",
 "description": "Ensure Project Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   { "name": "time_window", "query": "1m" },
   { "name": "kafka_topic", "query": "yolo_input" }
  ]
 },
 "panels": [
  { "title": "WORKLOAD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "I/O DELTA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"$kafka_topic\"}[$time_window]))by(topic) - sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"$kafka_topic\"}[$time_window]))by(topic)",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "KAFKA TOPIC: BYTES IN/OUT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"$kafka_topic\"}[$time_window]))by(topic)",
     "legendFormat": "BYTES IN"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"$kafka_topic\"}[$time_window]))by(topic) * -1",
     "legendFormat": "BYTES OUT"
    }
   ]
  },
  {
   "title": "LAST CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"worker.*\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"worker.*\"}[$time_window])))) * 100)) / 5",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "GLOBAL WORKER CPU USAGE (100% => 500%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"worker.*\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"worker.*\"}[$time_window])))) * 100)) / 5",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "LAST WATTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kepler_node_package_joules_total{instance=~\"worker.*\",mode=\"dynamic\"}[$time_window]))",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "GLOBAL WORKER WATTS (28W SOFT CAP PER NODE)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(irate(kepler_node_package_joules_total{instance=~\"worker.*\",mode=\"dynamic\"}[$time_window]))",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "LAST NUM PODS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) - count(kube_pod_info{namespace=~\"kube-system|kepler|monitoring|kafka\"})",
     "legendFormat": "Num Pods"
    }
   ]
  },
  {
   "title": "NUM PODS OVER TIME",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 2, "y": 16 },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) - count(kube_pod_info{namespace=~\"kube-system|kepler|monitoring|kafka\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "WORKLOAD POD CPU SECONDS",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\"}[$time_window])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "MASTER NODE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE (0-100%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"master\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"master\"}[$time_window])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "DISK USAGE (1000 GB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{instance=\"master\", device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"master\", device!~'rootfs'})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE (0-100%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker1\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker1\"}[$time_window])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "CUMULATIVE POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker1\"}[$time_window]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker1\",mode=\"dynamic\"}[$time_window])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "INDIVIDUAL POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 14, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker1\"}[$time_window])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "NUM PODS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 26 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker1\"}) - count(kube_pod_info{node=\"worker1\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE (0-100%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker2\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker2\"}[$time_window])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "CUMULATIVE POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker2\"}[$time_window]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker2\",mode=\"dynamic\"}[$time_window])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "INDIVIDUAL POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker2\"}[$time_window])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "NUM PODS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker1\"}) - count(kube_pod_info{node=\"worker2\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE (0-100%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker3\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker3\"}[$time_window])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "CUMULATIVE POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker3\"}[$time_window]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker3\",mode=\"dynamic\"}[$time_window])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "INDIVIDUAL POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 14, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker3\"}[$time_window])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "NUM PODS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 9 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker1\"}) - count(kube_pod_info{node=\"worker3\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE (0-100%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker4\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker4\"}[$time_window])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "CUMULATIVE POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker4\"}[$time_window]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker4\",mode=\"dynamic\"}[$time_window])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "INDIVIDUAL POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker4\"}[$time_window])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "NUM PODS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker1\"}) - count(kube_pod_info{node=\"worker4\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    }
   ]
  },
  {
   "title": "WORKER 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU USAGE (0-100%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"worker5\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"worker5\"}[$time_window])))) * 100",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "CUMULATIVE POD CPU SECONDS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker5\"}[$time_window]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU WATTS (0-35)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "irate(kepler_node_package_joules_total{instance=\"worker5\",mode=\"dynamic\"}[$time_window])",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "INDIVIDUAL POD CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\", node=\"worker5\"}[$time_window])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "NUM PODS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=\"worker1\"}) - count(kube_pod_info{node=\"worker5\", namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    }
   ]
  }
 ]
}