{
 "title": "Ensure CPU",
 "description": "Ensure Project Dashboard",
 "time": { "from": "2023-12-18T12:27:00.000Z", "to": "2023-12-18T13:28:00.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   { "name": "time_window", "query": "1m" },
   { "name": "kafka_topic", "query": "yolo_input" }
  ]
 },
 "panels": [
  {
   "title": "NODE DISTRIBUTION",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{node=~\"worker.*\", namespace=\"workload\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "NODE CPU SECONDS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{node=~\"worker.*\", namespace=\"workload\"}[$time_window])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "NODE DISTRIBUTION",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kepler_container_cpu_instructions_total{container_name=\"yolo-consumer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NODE CPU INSTRUCTIONS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "irate(kepler_container_cpu_instructions_total{container_name=\"yolo-consumer\"}[$time_window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NODE DISTRIBUTION",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kepler_container_cpu_cycles_total{container_name=\"yolo-consumer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NODE CPU CYCLES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "irate(kepler_container_cpu_cycles_total{container_name=\"yolo-consumer\"}[$time_window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OLD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "I/O DELTA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"$kafka_topic\"}[$time_window]))by(topic) - sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"$kafka_topic\"}[$time_window]))by(topic)) / sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"$kafka_topic\"}[$time_window]))by(topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "KAFKA TOPIC: BYTES IN/OUT",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 22, "x": 2, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"$kafka_topic\"}[$time_window]))by(topic)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"$kafka_topic\"}[$time_window]))by(topic) * -1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LAST CPU",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"worker.*\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"worker.*\"}[$time_window])))) * 100)) / 5",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "GLOBAL WORKER CPU USAGE (100% => 500%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 22, "x": 2, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"worker.*\",mode!=\"idle\"}[$time_window])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"worker.*\"}[$time_window])))) * 100)) / 5",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "LAST WATTS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(kepler_node_package_joules_total{instance=~\"worker.*\",mode=\"dynamic\"}[$time_window]))",
       "legendFormat": "Percent"
      }
     ]
    },
    {
     "title": "GLOBAL WORKER WATTS (28W SOFT CAP PER NODE)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 22, "x": 2, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(irate(kepler_node_package_joules_total{instance=~\"worker.*\",mode=\"dynamic\"}[$time_window]))",
       "legendFormat": "Watts"
      }
     ]
    },
    {
     "title": "LAST NUM PODS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{}) - count(kube_pod_info{namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": "Num Pods"
      }
     ]
    },
    {
     "title": "NUM PODS OVER TIME",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 2, "y": 23 },
     "targets": [
      {
       "expr": "count(kube_pod_info{}) - count(kube_pod_info{namespace=~\"kube-system|kepler|monitoring|kafka\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "WORKLOAD POD: LATEST CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 10, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=\"workload\"}[$time_window])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "WORKLOAD POD: TOTAL CPU SECONDS",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_cpu_usage_seconds_total{namespace=\"workload\"}",
       "legendFormat": " "
      }
     ]
    }
   ]
  }
 ]
}