version: '3.7'
services:

  cassandra_1:
    image: cassandra:4.1.0
    expose:
      - "7000" # intra-node communication
      - "7001" # TLS intra node communication
      - "7199" # JMX
      # - "9042" # CQL
      - "9142" # CQL TLS
      - "9160" # Thrift
    environment:
      CASSANDRA_CLUSTER_NAME: tutorials
      CASSANDRA_SEEDS: cassandra_1 #,cassandra_2,cassandra_3
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: DATACENTER1
      # HEAP_NEWSIZE: 8M
      # MAX_HEAP_SIZE: 512M
      # LOCAL_JMX: "no"
    ports: 
      - "12001:9042"
    volumes:
      - ./data:/var/lib/cassandra