apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
  name: workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-consumer-depl
  namespace: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-consumer
  template:
    metadata:
      labels:
        app: workload-consumer
    spec:
      containers:
      - name: workload-consumer-cont
        image: wickstjo/workload_consumer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

# kubectl apply -f workload-depl.yaml