apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - name: kafka-broker
        image: wurstmeister/kafka
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_BROKER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.index
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "10.106.50.127:2181"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://$(POD_NAME).kafka-service.kafka.svc.cluster.local:9092"